spring:
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: sensor-topic
          group: ${spring.application.name}
          consumer:
            useNativeEncoding: true

      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 8
        bindings:
          process-in-0:
            consumer:
              configuration:
                specific.avro.reader: true
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                auto.register.schemas: true

server:
  port: 0